deploymentMode: SingleBinary
loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 168h
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
gateway:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
monitoring:
  serviceMonitor:
    enabled: true
chunksCache:
  allocatedMemory: 256
resultsCache:
  allocatedMemory: 128
