deploymentMode: SingleBinary
loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 168h
singleBinary:
  replicas: 1
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
gateway:
  enabled: true
monitoring:
  serviceMonitor:
    enabled: true
chunksCache:
  allocatedMemory: 1024
resultsCache:
  allocatedMemory: 512
