apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: datacenter
  sources:
    - repoURL: https://charts.chaos-mesh.org
      chart: chaos-mesh
      targetRevision: 2.7.3
      helm:
        apiVersions:
          - cert-manager.io/v1
        valueFiles:
          - $values/platform/chaos/chaos-mesh/values.yaml
    - repoURL: https://github.com/billdotdev/datacenter.git
      targetRevision: main
      ref: values
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: chaos-controller-manager
      namespace: chaos-mesh
      jsonPointers:
        - /spec/template/metadata/annotations/rollme
    - group: apps
      kind: DaemonSet
      name: chaos-daemon
      namespace: chaos-mesh
      jsonPointers:
        - /spec/template/metadata/annotations/rollme
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: chaos-mesh-mutation
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: chaos-mesh-validation
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: chaos-mesh-validation-auth
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
